<?php

namespace Database\Seeders;

use App\Models\Student;
use Illuminate\Database\Seeder;

class StudentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $students = [
            [
                'id' => 1,
                'first_name' => 'Harry',
                'last_name' => 'Potter',
                'gender' => 'm',
                'birthday' => '1980-07-31',
                'house_id' => 4,
                'blood_status_id' => 3,
                'enrollment_date' => '1991-09-01',
                'graduation_date' => '1997-06-30',
                'diploma_id' => 2,
            ],
            [
                'id' => 2,
                'first_name' => 'Hermione',
                'last_name' => 'Granger',
                'gender' => 'm',
                'birthday' => '1972-09-19',
                'house_id' => 4,
                'blood_status_id' => 4,
                'enrollment_date' => '1991-09-01',
                'graduation_date' => '1999-06-30',
                'diploma_id' => 1,
            ],
            [
                'id' => 3,
                'first_name' => 'Ronald',
                'last_name' => 'Weasley',
                'gender' => 'm',
                'birthday' => '1980-03-01',
                'house_id' => 4,
                'blood_status_id' => 2,
                'enrollment_date' => '1991-09-01',
                'graduation_date' => '1997-06-30',
                'diploma_id' => 2,
            ],
            [
                'id' => 4,
                'first_name' => 'Neville',
                'last_name' => 'Longbottom',
                'gender' => 'm',
                'birthday' => '1980-07-30',
                'house_id' => 4,
                'blood_status_id' => 2,
                'enrollment_date' => '1991-09-01',
                'graduation_date' => '1997-06-30',
                'diploma_id' => 2,
            ],
            [
                'id' => 5,
                'first_name' => 'Dean',
                'last_name' => 'Thomas',
                'gender' => 'm',
                'birthday' => '1979-09-03',
                'house_id' => 4,
                'blood_status_id' => 3,
                'enrollment_date' => '1991-09-01',
                'graduation_date' => '1997-06-30',
                'diploma_id' => 2,
            ],
            [
                'id' => 6,
                'first_name' => 'Seamus',
                'last_name' => 'Finnigan',
                'gender' => 'm',
                'birthday' => '1980-08-30',
                'house_id' => 4,
                'blood_status_id' => 3,
                'enrollment_date' => '1991-09-01',
                'graduation_date' => '1997-06-30',
                'diploma_id' => 2,
            ],
            [
                'id' => 7,
                'first_name' => 'Padma',
                'last_name' => 'Patil',
                'gender' => 'f',
                'birthday' => '1979-12-15',
                'house_id' => 1,
                'blood_status_id' => 2,
                'enrollment_date' => '1991-09-01',
                'graduation_date' => '1997-06-30',
                'diploma_id' => 2,
            ],
            [
                'id' => 8,
                'first_name' => 'Paravati',
                'last_name' => 'Patil',
                'gender' => 'f',
                'birthday' => '1979-12-15',
                'house_id' => 4,
                'blood_status_id' => 2,
                'enrollment_date' => '1991-09-01',
                'graduation_date' => '1997-06-30',
                'diploma_id' => 2,
            ],
            [
                'id' => 9,
                'first_name' => 'Lavender',
                'last_name' => 'Brown',
                'gender' => 'f',
                'birthday' => '1979-02-17',
                'house_id' => 4,
                'blood_status_id' => 2,
                'enrollment_date' => '1991-09-01',
                'graduation_date' => '1997-06-30',
                'diploma_id' => 2,
            ],
            [
                'id' => 10,
                'first_name' => 'Draco',
                'last_name' => 'Malfoy',
                'gender' => 'm',
                'birthday' => '1980-06-05',
                'house_id' => 2,
                'blood_status_id' => 2,
                'enrollment_date' => '1991-09-01',
                'graduation_date' => '1997-06-30',
                'diploma_id' => 2,
            ],
            [
                'id' => 11,
                'first_name' => 'Vincent',
                'last_name' => 'Crabbe',
                'gender' => 'm',
                'birthday' => '1979-08-13',
                'house_id' => 2,
                'blood_status_id' => 2,
                'enrollment_date' => '1991-09-01',
                'graduation_date' => '1997-06-30',
                'diploma_id' => 2,
            ],
            [
                'id' => 12,
                'first_name' => 'Gregory',
                'last_name' => 'Goyle',
                'gender' => 'm',
                'birthday' => '1979-10-13',
                'house_id' => 2,
                'blood_status_id' => 2,
                'enrollment_date' => '1991-09-01',
                'graduation_date' => '1997-06-30',
                'diploma_id' => 2,
            ],
            [
                'id' => 13,
                'first_name' => 'Pansy',
                'last_name' => 'Parkinson',
                'gender' => 'f',
                'birthday' => '1979-10-01',
                'house_id' => 2,
                'blood_status_id' => 2,
                'enrollment_date' => '1991-09-01',
                'graduation_date' => '1997-06-30',
                'diploma_id' => 2,
            ],
            [
                'id' => 14,
                'first_name' => 'Blaise',
                'last_name' => 'Zabini',
                'gender' => 'm',
                'birthday' => '1979-09-02',
                'house_id' => 2,
                'blood_status_id' => 2,
                'enrollment_date' => '1991-09-01',
                'graduation_date' => '1997-06-30',
                'diploma_id' => 2,
            ],
            [
                'id' => 15,
                'first_name' => 'Daphne',
                'last_name' => 'Greengrass',
                'gender' => 'f',
                'birthday' => '1979-09-29',
                'house_id' => 2,
                'blood_status_id' => 2,
                'enrollment_date' => '1991-09-01',
                'graduation_date' => '1997-06-30',
                'diploma_id' => 2,
            ],
            [
                'id' => 16,
                'first_name' => 'Tracey',
                'last_name' => 'Davis',
                'gender' => 'f',
                'birthday' => '1979-11-18',
                'house_id' => 2,
                'blood_status_id' => 3,
                'enrollment_date' => '1991-09-01',
                'graduation_date' => '1997-06-30',
                'diploma_id' => 2,
            ],
            [
                'id' => 17,
                'first_name' => 'Millicent',
                'last_name' => 'Bulstrode',
                'gender' => 'f',
                'birthday' => '1979-09-22',
                'house_id' => 2,
                'blood_status_id' => 3,
                'enrollment_date' => '1991-09-01',
                'graduation_date' => '1997-06-30',
                'diploma_id' => 2,
            ],
            [
                'id' => 18,
                'first_name' => 'Mandy',
                'last_name' => 'Brocklehurst',
                'gender' => 'f',
                'birthday' => '1980-02-01',
                'house_id' => 1,
                'blood_status_id' => 3,
                'enrollment_date' => '1991-09-01',
                'graduation_date' => '1997-06-30',
                'diploma_id' => 2,
            ],
            [
                'id' => 19,
                'first_name' => 'Sue',
                'last_name' => 'Li',
                'gender' => 'f',
                'birthday' => '1980-03-29',
                'house_id' => 1,
                'blood_status_id' => 3,
                'enrollment_date' => '1991-09-01',
                'graduation_date' => '1997-06-30',
                'diploma_id' => 2,
            ],
            [
                'id' => 20,
                'first_name' => 'Morag',
                'last_name' => 'MacDougal',
                'gender' => 'f',
                'birthday' => '1979-10-25',
                'house_id' => 1,
                'blood_status_id' => 2,
                'enrollment_date' => '1991-09-01',
                'graduation_date' => '1997-06-30',
                'diploma_id' => 2,
            ],
            [
                'id' => 21,
                'first_name' => 'Lisa',
                'last_name' => 'Turpin',
                'gender' => 'f',
                'birthday' => '1979-12-31',
                'house_id' => 1,
                'blood_status_id' => 2,
                'enrollment_date' => '1991-09-01',
                'graduation_date' => '1997-06-30',
                'diploma_id' => 2,
            ],
            [
                'id' => 22,
                'first_name' => 'Terry',
                'last_name' => 'Boot',
                'gender' => 'm',
                'birthday' => '1979-09-04',
                'house_id' => 1,
                'blood_status_id' => 3,
                'enrollment_date' => '1991-09-01',
                'graduation_date' => '1997-06-30',
                'diploma_id' => 2,
            ],
            [
                'id' => 23,
                'first_name' => 'Michael',
                'last_name' => 'Corner',
                'gender' => 'm',
                'birthday' => '1979-10-23',
                'house_id' => 1,
                'blood_status_id' => 3,
                'enrollment_date' => '1991-09-01',
                'graduation_date' => '1997-06-30',
                'diploma_id' => 2,
            ],
            [
                'id' => 24,
                'first_name' => 'Anthony',
                'last_name' => 'Goldstein',
                'gender' => 'm',
                'birthday' => '1979-10-23',
                'house_id' => 1,
                'blood_status_id' => 2,
                'enrollment_date' => '1991-09-01',
                'graduation_date' => '1997-06-30',
                'diploma_id' => 2,
            ],
            [
                'id' => 25,
                'first_name' => 'Hannah',
                'last_name' => 'Abbott',
                'gender' => 'f',
                'birthday' => '1979-09-30',
                'house_id' => 3,
                'blood_status_id' => 2,
                'enrollment_date' => '1991-09-01',
                'graduation_date' => '1997-06-30',
                'diploma_id' => 2,
            ],
            [
                'id' => 26,
                'first_name' => 'Susan',
                'last_name' => 'Bones',
                'gender' => 'f',
                'birthday' => '1979-09-29',
                'house_id' => 3,
                'blood_status_id' => 2,
                'enrollment_date' => '1991-09-01',
                'graduation_date' => '1997-06-30',
                'diploma_id' => 2,
            ],
            [
                'id' => 27,
                'first_name' => 'Justin',
                'last_name' => 'Finch-Fletchley',
                'gender' => 'm',
                'birthday' => '1979-10-28',
                'house_id' => 3,
                'blood_status_id' => 2,
                'enrollment_date' => '1991-09-01',
                'graduation_date' => '1997-06-30',
                'diploma_id' => 2,
            ],
            [
                'id' => 28,
                'first_name' => 'Ernest',
                'last_name' => 'Macmillan',
                'gender' => 'm',
                'birthday' => '1980-04-23',
                'house_id' => 3,
                'blood_status_id' => 2,
                'enrollment_date' => '1991-09-01',
                'graduation_date' => '1997-06-30',
                'diploma_id' => 2,
            ],
            [
                'id' => 29,
                'first_name' => 'Cho',
                'last_name' => 'Chang',
                'gender' => 'f',
                'birthday' => '1978-10-10',
                'house_id' => 1,
                'blood_status_id' => 2,
                'enrollment_date' => '1990-09-01',
                'graduation_date' => '1996-06-30',
                'diploma_id' => 2,
            ],
            [
                'id' => 30,
                'first_name' => 'Angelina',
                'last_name' => 'Johnson',
                'gender' => 'f',
                'birthday' => '1977-10-28',
                'house_id' => 4,
                'blood_status_id' => 2,
                'enrollment_date' => '1988-09-01',
                'graduation_date' => '1995-06-30',
                'diploma_id' => 1,
            ],
            [
                'id' => 31,
                'first_name' => 'Fred',
                'last_name' => 'Weasley',
                'gender' => 'm',
                'birthday' => '1978-04-01',
                'house_id' => 4,
                'blood_status_id' => 2,
                'enrollment_date' => '1989-09-01',
                'graduation_date' => '1995-06-30',
                'diploma_id' => 2,
            ],
            [
                'id' => 32,
                'first_name' => 'George',
                'last_name' => 'Weasley',
                'gender' => 'm',
                'birthday' => '1978-04-01',
                'house_id' => 4,
                'blood_status_id' => 2,
                'enrollment_date' => '1989-09-01',
                'graduation_date' => '1995-06-30',
                'diploma_id' => 2,
            ],
            [
                'id' => 33,
                'first_name' => 'Ginevra',
                'last_name' => 'Weasley',
                'gender' => 'f',
                'birthday' => '1981-08-11',
                'house_id' => 4,
                'blood_status_id' => 2,
                'enrollment_date' => '1992-09-01',
                'graduation_date' => '1997-06-30',
                'diploma_id' => 2,
            ],
            [
                'id' => 34,
                'first_name' => 'Luna',
                'last_name' => 'Lovegood',
                'gender' => 'f',
                'birthday' => '1981-02-13',
                'house_id' => 1,
                'blood_status_id' => 2,
                'enrollment_date' => '1992-09-01',
                'graduation_date' => '1997-06-30',
                'diploma_id' => 2,
            ],
            [
                'id' => 35,
                'first_name' => 'Adrian',
                'last_name' => 'Pucey',
                'gender' => 'm',
                'birthday' => '1977-12-28',
                'house_id' => 2,
                'blood_status_id' => 2,
                'enrollment_date' => '1988-09-01',
                'graduation_date' => '1997-06-30',
                'diploma_id' => null,
            ],
            [
                'id' => 36,
                'first_name' => 'Marcus',
                'last_name' => 'Flint',
                'gender' => 'm',
                'birthday' => '1975-11-11',
                'house_id' => 2,
                'blood_status_id' => 2,
                'enrollment_date' => '1986-09-01',
                'graduation_date' => '1996-06-30',
                'diploma_id' => null,
            ],
            [
                'id' => 37,
                'first_name' => 'Cedric',
                'last_name' => 'Diggory',
                'gender' => 'm',
                'birthday' => '1977-10-29',
                'house_id' => 3,
                'blood_status_id' => 2,
                'enrollment_date' => '1988-09-01',
                'graduation_date' => '1995-06-24',
                'diploma_id' => 2,
            ],
            [
                'id' => 38,
                'first_name' => 'Zacharias',
                'last_name' => 'Smith',
                'gender' => 'm',
                'birthday' => '1981-01-01',
                'house_id' => 3,
                'blood_status_id' => 3,
                'enrollment_date' => '1992-09-01',
                'graduation_date' => '1997-06-30',
                'diploma_id' => 2,
            ],
            [
                'id' => 39,
                'first_name' => 'Percy',
                'last_name' => 'Weasley',
                'gender' => 'm',
                'birthday' => '1976-08-22',
                'house_id' => 4,
                'blood_status_id' => 2,
                'enrollment_date' => '1987-09-01',
                'graduation_date' => '1994-06-30',
                'diploma_id' => 1,
            ],
            [
                'id' => 40,
                'first_name' => 'Roger',
                'last_name' => 'Davies',
                'gender' => 'm',
                'birthday' => '1977-09-08',
                'house_id' => 1,
                'blood_status_id' => 2,
                'enrollment_date' => '1988-09-01',
                'graduation_date' => '1997-06-30',
                'diploma_id' => 1,
            ],
            [
                'id' => 41,
                'first_name' => 'Amy',
                'last_name' => 'Wellington',
                'gender' => 'f',
                'birthday' => '1980-04-10',
                'house_id' => 1,
                'blood_status_id' => 2,
                'enrollment_date' => '1992-09-01',
                'graduation_date' => '1996-06-30',
                'diploma_id' => null,
            ],
            [
                'id' => 42,
                'first_name' => 'Lily',
                'last_name' => 'Wellington',
                'gender' => 'f',
                'birthday' => '1978-03-01',
                'house_id' => 4,
                'blood_status_id' => 2,
                'enrollment_date' => '1992-09-01',
                'graduation_date' => '1996-06-30',
                'diploma_id' => null,
            ],
            [
                'id' => 43,
                'first_name' => 'Xenia',
                'last_name' => 'Vangelisou',
                'gender' => 'f',
                'birthday' => '1976-12-24',
                'house_id' => 2,
                'blood_status_id' => 1,
                'enrollment_date' => '1987-09-01',
                'graduation_date' => '1994-06-30',
                'diploma_id' => 1,
            ],
            [
                'id' => 44,
                'first_name' => 'Vanessa',
                'last_name' => 'Harbor',
                'gender' => 'f',
                'birthday' => '1974-12-01',
                'house_id' => 1,
                'blood_status_id' => 3,
                'enrollment_date' => '1985-09-01',
                'graduation_date' => '1992-06-30',
                'diploma_id' => 1,
            ],
            [
                'id' => 45,
                'first_name' => 'Julia',
                'last_name' => 'Nakamura',
                'gender' => 'f',
                'birthday' => '1979-05-08',
                'house_id' => 1,
                'blood_status_id' => 4,
                'enrollment_date' => '1990-09-01',
                'graduation_date' => '1997-06-30',
                'diploma_id' => 1,
            ],
            [
                'id' => 46,
                'first_name' => 'July',
                'last_name' => 'Kennedy',
                'gender' => 'f',
                'birthday' => '1976-07-12',
                'house_id' => 3,
                'blood_status_id' => 4,
                'enrollment_date' => '1987-09-01',
                'graduation_date' => '1994-06-30',
                'diploma_id' => 1,
            ],
            [
                'id' => 47,
                'first_name' => 'Sakura',
                'last_name' => 'Yamamura',
                'gender' => 'f',
                'birthday' => '1980-01-01',
                'house_id' => 2,
                'blood_status_id' => 1,
                'enrollment_date' => '1994-09-01',
                'graduation_date' => '1995-06-30',
                'diploma_id' => 4,
            ],
            [
                'id' => 48,
                'first_name' => 'Christian',
                'last_name' => 'Cornwall',
                'gender' => 'm',
                'birthday' => '1979-02-20',
                'house_id' => 1,
                'blood_status_id' => 2,
                'enrollment_date' => '1990-09-01',
                'graduation_date' => '1997-06-30',
                'diploma_id' => 1,
            ],
            [
                'id' => 49,
                'first_name' => 'Luke',
                'last_name' => 'Marquadt',
                'gender' => 'm',
                'birthday' => '1980-04-01',
                'house_id' => 2,
                'blood_status_id' => 4,
                'enrollment_date' => '1994-09-01',
                'graduation_date' => '1995-06-30',
                'diploma_id' => 4,
            ],
            [
                'id' => 50,
                'first_name' => 'Max',
                'last_name' => 'Smith',
                'gender' => 'm',
                'birthday' => '1973-08-20',
                'house_id' => 4,
                'blood_status_id' => 4,
                'enrollment_date' => '1988-09-01',
                'graduation_date' => '1989-06-30',
                'diploma_id' => 4,
            ],
        ];

        foreach ($students as $student) {
            Student::updateOrCreate(['id' => $student['id']], $student);
        }
    }
}
